server:
  port: 8181
logging:
  level:
    root: info

spring: 
  datasource:  
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://localhost:3306/jiaoke_location?characterEncoding=utf8&useSSL=false  
    username: root  
    password: 123  
    driver-class-name: com.mysql.jdbc.Driver   
mybatis:   
  mapperLocations: classpath*:mybatis/mapper-*.xml  
  typeAliasesPackage: com.jiaoke.bean
